### ISSUE TITLE
Refresh?

### ISSUE THREAD

**Issue by EionRobb** [avaidyam/GoogleAPIProtobufs#1]
What method/software did you use to generate these protobufs, and can they be refreshed with latest?

**Comment by avaidyam** [comment]
You'll need to locate the IPA for the app you're interested in, then crack/patch/decrypt that IPA, then explore to find any `.proto` files, and if not, find the root `descriptor` class and walk down the tree of message declarations there. It's unfortunately a LOT of effort and I no longer have any of the scripts I previously used for this effort available.

**Comment by EionRobb** [comment]
Ah, that's a shame that the scripts aren't around.  I've got the other steps sorted, but been decoding by hand.

Thanks anyway :)
